#language: objective-c
#install:
#  - ./build-libssl.sh --noverify
#  - ./build-libevent.sh --noverify
#  - ./build-tor.sh --noverify
#  - ./OnionBrowser/icon/install.sh
#
#xcode_project: OnionBrowser/OnionBrowser.xcodeproj
#xcode_scheme: OnionBrowser
#notifications:
#  email: false
