language: objective-c
install:
  - ./build-libssl.sh --noverify --i386only
  - ./build-libevent.sh --noverify --i386only
  - ./build-tor.sh --noverify --i386only
  - ./OnionBrowser/icon/install.sh

before_script:
  - brew update
  - brew upgrade xctool
script:
  - xctool -project OnionBrowser/OnionBrowser.xcodeproj -scheme OnionBrowser -sdk iphonesimulator7.1 -arch i386 build test -resetSimulator -freshSimulator -freshInstall

notifications:
  email: false
