language: objective-c
install:
  - ./build-libssl.sh
  - ./build-libevent.sh
  - ./build-tor.sh
  - ./OnionBrowser/icon/install.sh

xcode_project: OnionBrowser/OnionBrowser.xcodeproj
xcode_scheme: OnionBrowser
notifications:
  email: false
