language: objective-c
install:
  - ./build-libssl.sh --noverify --i386only
  - ./build-libevent.sh --noverify --i386only
  - ./build-tor.sh --noverify --i386only
  - ./OnionBrowser/icon/install.sh

xcode_project: OnionBrowser/OnionBrowser.xcodeproj
xcode_scheme: OnionBrowser
xcode_sdk: iphonesimulator
notifications:
  email: false
